tinymce.addI18n('ru',{
  'AI Assistant': 'Ассистент ИИ',
  'Ask AI to edit or generate...': 'Попросите сгенерировать или отредактировать ...',
  'Generate': 'Сгенерировать',
  'Ask Ai': 'Ассистент ИИ',
  'AI responses can be inaccurate': 'ИИ может допускать ошибки.',
  'Try again': 'Еще раз',
  'Stop': 'Стоп',
  'Summarize content': 'Резюмировать текст',
  'Improve writing': 'Улучшить текст',
  'Simplify language': 'Упростить текст',
  'Expand upon': 'Расширить текст',
  'Trim content': 'Сократить текст',
  'Change tone': 'Изменить тон',
  'Professional': 'На профессиональный',
  'Casual': 'На непринужденный',
  'Direct': 'На прямой',
  'Confident': 'На уверенный',
  'Friendly': 'На дружеский',
  'Change style': 'Изменить стиль',
  'Business': 'На деловой',
  'Legal': 'На юридический',
  'Journalism': 'На журналистский',
  'Medical': 'На медицинский',
  'Poetic': 'На поэтический',
  'Translate': 'Перевести',
  'Translate to English': 'Перевести на Английский',
  'Translate to Russian': 'Перевести на Русский',
  'Translate to Ukrainian': 'Перевести на Украинский',
  'Translate to German': 'Перевести на Немецкий',
  'Translate to Spanish': 'Перевести на Испанский',
  'Translate to Portuguese': 'Перевести на Португальский',
  'Translate to French': 'Перевести на Французский',
  'Translate to Norwegian': 'Перевести на Норвежский',
  'Translate to Japanese': 'Перевести на Японский',
  'Translate to Korean': 'Перевести на Корейский',
  'Translate to Simplified Chinese': 'Перевести на упрощенный Китайский',
  'Translate to Hebrew': 'Перевести на Иврит',
  'Translate to Hindi': 'Перевести на Хинди',
  'Translate to Arabic': 'Перевести на Арабский',
  'Ai shortcuts': 'Быстрые команды ИИ',
});