tinymce.addI18n('uk', {
  'AI Assistant': 'Асистент ШІ',
  'Ask AI to edit or generate...': 'Попросіть створити або відредагувати ...',
  'Generate': 'Згенерувавши',
  'Ask Ai': 'Асистент ШІ',
  'AI responses can be inaccurate': 'Відповіді ШІ можуть бути неточними',
  'Try again': 'Ще раз',
  'Stop': 'Стоп',
  'Summarize content': 'Резюмувати текст',
  'Improve writing': 'Поліпшити текст',
  'Simplify language': 'Спростити текст',
  'Expand upon': 'Розширити текст',
  'Trim content': 'Скоротити текст',
  'Change tone': 'Змінити тон',
  'Professional': 'На професійний',
  'Casual': 'На невимушений',
  'Direct': 'На прямій',
  'Confident': 'На впевнений',
  'Friendly': 'На дружній',
  'Change style': 'Змінити стиль',
  'Business': 'На діловій',
  'Legal': 'На юридичний',
  'Journalism': 'На журналістський',
  'Medical': 'На медичний',
  'Poetic': 'На поетичний',
  'Translate': 'Перевівши',
  'Translate to English': 'Перекласти на англійську',
  'Translate to Russian': 'Перекласти на російську',
  'Translate to Ukrainian': 'Перекласти українською',
  'Translate to German': 'Перекласти на німецьку',
  'Translate to Spanish': 'Перекласти на іспанську',
  'Translate to Portuguese': 'Перекласти на португальську',
  'Translate to French': 'Перекласти на французьку',
  'Translate to Norwegian': 'Перекласти на норвезьку',
  'Translate to Japanese': 'Перекласти на японську',
  'Translate to Korean': 'Перекласти на корейську',
  'Translate to Simplified Chinese': 'Перекласти на спрощену китайську',
  'Translate to Hebrew': 'Перекласти на іврит',
  'Translate to Hindi': 'Перекласти на хінді',
  'Translate to Arabic': 'Перекласти на арабську',
  'Ai shortcuts': 'Швидкі команди ШІ',
});